schema:
  openapi:  3.0.2
  components:
    schemas:
      Tunnel: &Tunnel
        type: object
        properties:
          name:
            type: string
            description: "tunnel name override"
          replicaCount:
            type: integer
            description: "tunnel replica count"
            default: 1
          ssh:
            type: object
            properties:
              server:
                type: string
                description: "server name"
              port:
                type: integer
                description: "server port"
              user:
                type: string
                description: "server user"
          remote:
            type: object
            properties:
              service:
                type: string
                description: "remote service address"
              port:
                type: integer
                description: "remote service port"
          local:
            type: object
            properties:
              service:
                type: string
                description: "local service name"
              namespace:
                type: string
                description: "local service namespace"
              port:
                type: integer
                description: "local service port; defaults to remote.port"
              port_name:
                type: string
                description: "local service port name"
      ClientVars:
        type: object
        required:
          - tunnels
        properties:
          chart_version:
            type: string
            description: "sshts chart version"          
          nodeSelector: !include core:schema/k8s.yaml#/components/schemas/NodeSelector
          tolerations: !include core:schema/k8s.yaml#/components/schemas/Tolerations
          tunnels:
            type: array
            items: *Tunnel

      Client2Vars:
        type: object
        required:
          - tunnels
        properties:
          chart_version:
            type: string
            description: "sshts chart version"          
          nodeSelector: !include core:schema/k8s.yaml#/components/schemas/NodeSelector
          tolerations: !include core:schema/k8s.yaml#/components/schemas/Tolerations
          tunnels:
            type: object
            additionalProperties: *Tunnel
            
      SSHKeys:
        type: object
        required:
          - id_ecdsa
          - id_ecdsa.pub
        properties:
          id_ecdsa:
            type: string
            description: "id_ecdsa private key"
          id_ecdsa.pub:
            type: string
            description: "id_ecdsa public key"
      ServerVars:
        type: object
        required:          
          - run_on_control_plain          
        properties:          
          chart_version:
            type: string
            description: "sshts chart version"
          run_on_control_plain:
            type: boolean
            description: "run sshts on control plain"          
          nodeSelector: !include core:schema/k8s.yaml#/components/schemas/NodeSelector
          tolerations: !include core:schema/k8s.yaml#/components/schemas/Tolerations
          server_authorized_keys:            
            type: object
            description: "user static or vault authorized keys"
            properties:
              static:
                type: array
                description: "static authorized keys"
                items:
                  type: string
              vault:
                type: array
                items:
                  type: object
                  description: "vault authorized keys"
                  properties:
                    path:
                      type: string
                      description: "vault secret path"
                    key:
                      type: string
                      description: "vault secret key"


modules:
  clients:
    src: sshts:stack/client/
    providers: [vault, kubernetes, helm, cluster_secret]
    secrets:
      ssh:
        secret_type: SSHKeys
        required: true
    schemas:
      vars: ClientVars
    vars:
      chart_path: '{{stackd.resolve_path("sshts:charts/sshts")}}'
  
  tunnels:
    src: sshts:stack/client2/
    providers: [vault, kubernetes, helm, cluster_secret]
    secrets:
      ssh:
        secret_type: SSHKeys
        required: true
    schemas:
      vars: Client2Vars
    vars:
      chart_path: '{{stackd.resolve_path("sshts:charts/sshts")}}'

  server:
    src: sshts:stack/server/
    providers: [vault, kubernetes, helm, cluster_secret]    
    schemas:
      vars: ServerVars
    vars:
      chart_path: '{{stackd.resolve_path("sshts:charts/sshts")}}'
      run_on_control_plain: true