name: Build docker image for docker-* tags

on:
  push:
    tags:
      - '*'
    
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:

  build-and-publish-tag:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
#    if: startsWith(github.ref, 'refs/tags/docker-') # Running this job only for tags

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true          
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }},${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          context: docker
          platforms: linux/amd64,linux/arm64